In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from main import *

100%|██████████| 986/986 [00:00<00:00, 5863.71it/s]


In [3]:
print(*config.items(), sep='\n')

('model_name', 'LSTM_3')
('feature', 'max-length')
('max_len', 48)
('min_freq_src', 1)
('min_freq_trg', 5)
('embedding_dim', 192)
('hidden_size', 384)
('num_layers', 3)
('num_epochs', 15)
('weight_decay', 0.001)
('label_smoothing', 0.3)
('dropout_emb', 0.1)
('dropout_enc', 0.2)
('dropout_dec', 0.2)
('dropout_attention', 0.1)
('learning_rate', 0.001)
('lr_manual_decrease', False)
('amsgrad', False)
('gamma', 0.5)
('patience', 1)
('threshold', 0.001)
('batch_size', 128)
('use_tf', False)
('tf_from_epoch', 0)
('tf_start', 0.9)
('tf_decrease', 0.02)
('weights', '../weights/saves/lstm-save-10.pt')
('src_vocab_size', 24673)
('trg_vocab_size', 18711)


In [4]:
from dataset2 import TrainDataLoader, TestDataLoader
from config import filenames, folders
from lstm3 import LSTM_3

In [5]:
unk_idx, pad_idx, bos_idx, eos_idx = 0, 1, 2, 3
device = 'cuda'

train_loader = TrainDataLoader(train_dataset, shuffle=True)
val_loader = TestDataLoader(val_dataset, shuffle=False)

weights_filename = folders['weights'] + 'saves/lstm-save-15.pt'

model = LSTM_3(config=config).to(device)
print(model)
print(model.count_parameters())

LSTM_3(
  (src_embedding): Embedding(24673, 192, padding_idx=1)
  (trg_embedding): Embedding(18711, 192, padding_idx=1)
  (emb_dropout): Dropout(p=0.1, inplace=False)
  (enc_dropout): Dropout(p=0.2, inplace=False)
  (dec_dropout): Dropout(p=0.2, inplace=False)
  (attention_dropout): Dropout(p=0.1, inplace=False)
  (encoder): LSTM(192, 384, num_layers=3, batch_first=True, dropout=0.2, bidirectional=True)
  (encoder_output_proj): Linear(in_features=768, out_features=384, bias=True)
  (decoder): LSTM(192, 384, num_layers=3, batch_first=True, dropout=0.2)
  (encoder_hidden_proj): ModuleList(
    (0-2): 3 x Linear(in_features=768, out_features=384, bias=True)
  )
  (encoder_cell_proj): ModuleList(
    (0-2): 3 x Linear(in_features=768, out_features=384, bias=True)
  )
  (fc): Linear(in_features=768, out_features=18711, bias=True)
  (emb_layer_norm): LayerNorm((192,), eps=1e-05, elementwise_affine=True)
  (encoder_output_norm): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
  (decoder

In [6]:
model.demonstrate(val_loader, vocab_src, vocab_trg, examples=3, wait=1, verbose=1, beam_width=5)

k: 5	B: 1	max_len: 27
beam tokens:
<BOS>|▁als |▁ich |▁11  |▁jahre|▁alt |▁war |▁,   |▁wurde|▁ich |▁eines|▁morge|▁von |▁den |▁kl  |ängen|▁helle|▁freud|▁gewec|▁.   |<EOS>
index in batch: 0
8.4890|2.3135|2.0933|4.2264|5.7495

	beam probability: 0.00
<BOS>|and  |when |i    |was  |<NUM>|years|old  |,    |i    |became|a    |mornin|from |my   |little|bottle|of   |happin|.    |<EOS>|<PAD>|<PAD>|<PAD>|<PAD>
100.0|8.21 |49.66|6.72 |36.79|4.98 |22.31|3.69 |14.96|0.82 |0.33 |0.17 |0.06 |0.01 |0.01 |0.0  |0.0  |0.0  |0.0  |0.0  |0.0  |0.0  |0.0  |0.0  |0.0  
	beam probability: 0.00
<BOS>|and  |when |i    |was  |<NUM>|years|old  |,    |i    |became|a    |mornin|from |the  |top  |of   |my   |favori|happin|.    |<EOS>|<PAD>|<PAD>|<PAD>
100.0|8.21 |49.66|6.72 |36.79|4.98 |22.31|3.69 |14.96|0.82 |0.33 |0.17 |0.06 |0.01 |0.01 |0.0  |0.0  |0.0  |0.0  |0.0  |0.0  |0.0  |0.0  |0.0  |0.0  
	beam probability: 0.00
<BOS>|and  |when |i    |was  |<NUM>|years|old  |,    |i    |became|a    |mornin|from |the  |top  

In [ ]:
train_dataset = TranslationDataset(vocab_src, 
                                vocab_trg, 
                                filenames['train_src'], 
                                filenames['train_trg'], 
                                max_len=config['max_len'], 
                                device=device,
                                sort_lengths=True)

val_dataset = TranslationDataset(vocab_src, 
                                vocab_trg, 
                                filenames['test_src'], 
                                filenames['test_trg'], 
                                max_len=72, 
                                device=device, 
                                sort_lengths=True)

100%|██████████| 986/986 [00:00<00:00, 5460.66it/s]


In [12]:
train_dataset.ids

[893,
 895,
 1633,
 1635,
 4639,
 5343,
 5347,
 8445,
 11333,
 17357,
 21919,
 26154,
 26579,
 32678,
 33102,
 37094,
 41286,
 41432,
 43961,
 44926,
 45714,
 47897,
 48620,
 48931,
 50418,
 51166,
 51398,
 51400,
 51424,
 51900,
 52473,
 53154,
 53550,
 54117,
 54134,
 55327,
 55624,
 62066,
 66038,
 66959,
 67527,
 69269,
 69963,
 70007,
 72903,
 78154,
 79664,
 79672,
 83926,
 85186,
 85545,
 85874,
 89233,
 89968,
 92153,
 92284,
 94362,
 96200,
 97717,
 102052,
 103652,
 103981,
 116640,
 116920,
 117100,
 117568,
 124348,
 130566,
 133004,
 136992,
 139819,
 141215,
 145414,
 145891,
 148219,
 150004,
 154976,
 155950,
 162718,
 163160,
 164800,
 168230,
 168268,
 168928,
 169384,
 170598,
 170659,
 171389,
 171734,
 172985,
 172986,
 173016,
 174335,
 174379,
 175923,
 182422,
 182432,
 183678,
 184735,
 1774,
 2504,
 2544,
 3293,
 4004,
 4438,
 4803,
 6317,
 6985,
 7001,
 7059,
 7569,
 7613,
 8040,
 9712,
 10678,
 10820,
 11294,
 11381,
 12504,
 13638,
 15957,
 18123,
 20633,
 

In [24]:
from submission import get_bleu
from dataset2 import RawDataset
raw_dataset_val = RawDataset(filenames['test_trg'])
raw_dataset_val.src = [raw_dataset_val.src[i] for i in val_dataset.ids]
raw_dataset_train = RawDataset(filenames['train_trg'], n=int(15e5))
raw_dataset_train.src = [raw_dataset_train.src[i] for i in train_dataset.ids[:int(5e2)+1]]
bleu, sinergy, bp = get_bleu(model, val_dataset, raw_dataset_val, vocab_trg, vocab_src, n=int(1e4), use_beam=True, beam_width=1)
print(f'BLEU4: {bleu:0.2f}')

1000
1500000


8it [00:12,  1.56s/it]

correct:	 12624 6687 3899 2351
total:		 22365 21379 20394 19411
sinergy:	25.29
BP:		1
56.4/31.3/19.1/12.1
BLEU4: 25.29


In [18]:
from submission import bad_bleu
val_loader = TestDataLoader(val_dataset, batch_size=128)
bleu = bad_bleu(model, val_loader, vocab_trg, vocab_src, raw_dataset, n=1e3, use_beam=False, beam_width=10)
print(f'BLEU4: {bleu:0.2f}')

calculating bleu...


  0%|          | 0/8 [00:07<?, ?it/s]


TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

In [10]:
from submission import make_submission
from dataset2 import SubmissionDataLoader, SubmissionDataset, RawDataset
raw_dataset = RawDataset(filenames['submission_src'])
submission_dataset = SubmissionDataset(filenames['submission_src'], vocab=vocab_src)
submission_loader = SubmissionDataLoader(submission_dataset)
make_submission(model, submission_loader=submission_loader, raw_dataset=raw_dataset, vocab_trg=vocab_trg, vocab_src=vocab_src, filenames=filenames)

100%|██████████| 24/24 [00:39<00:00,  1.65s/it]


In [95]:
src = "also , als fotografen wissen sie , wenn sie ein foto mit kurzer <UNK> machen , haben sie sehr wenig licht , aber wir <UNK> eine milliarde mal schneller als ihre kürzeste <UNK> , also bekommen sie so gut wie gar kein licht ."
model.translate(src, vocab_src, vocab_trg, beams=5, verbose=1, border=0.00)

k: 5	B: 1	max_len: 48
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0], device='cud

"so , as you know , if you know a photograph with a short amount of light , they 're very little light , but we 're going to make a billion times faster than your pure counterparts , so"

In [88]:
len(src.split())

44

In [94]:
import torch
import numpy as np
a = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device='cpu')
b = torch.tensor([1, 2], dtype=torch.long)
a.masked_fill((a>0), 0)
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [119]:
val_loader = TestDataLoader(val_dataset, batch_size=512, shuffle=True)


In [129]:
model.demonstrate(val_loader, vocab_src, vocab_trg, examples=10, wait=0, beam_width=10)

src:		 ich will einen ganzen an gärten pflanzen , wo menschen das essen im selben block teilen können .
trg:		 i want to plant a whole block of gardens where people can share in the food in the same block .
pred:		 i want to make a whole of gardens , where people can share the food , where people can share the food in the same block , and the way people
pred-beam:	 i want to put a whole bunch of gardens , which is where people can share the way , where people can share .
bleu:		29.49
bleu beam:	18.09

src:		 aber leider muss ich ihnen mitteilen , dass im jahr <NUM> ein sehr doktorand der nyu alle models auf dem gezählt hat , jedes einzelne , das gebucht wurde , und dass von <NUM> models nur <NUM> oder weniger als vier prozent nicht weiß waren .
trg:		 but unfortunately i have to inform you that in <NUM> , a very inspired nyu ph.d. student counted all the models on the runway , every single one that was hired , and of the <NUM> models that were hired , only <NUM> , or less than four per

In [ ]:
5e3

5000.0